services:
  db:
    image: postgres:16
    container_name: timecrax_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME:-timecrax}
      POSTGRES_USER: ${DB_USER:-timecrax}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-}
    volumes:
      - timecrax_pgdata:/var/lib/postgresql/data
    networks:
      - app
      - internal

  pgadmin:
    image: dpage/pgadmin4:8
    container_name: timecrax_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "127.0.0.1:5050:80"
    networks:
      - app
    volumes:
      - timecrax_pgadmin_data:/var/lib/pgadmin
    depends_on:
      - db

  api:
    build:
      context: ../src/Timecrax.Api
      dockerfile: Dockerfile
    container_name: timecrax_api
    restart: unless-stopped
    ports:
      - "127.0.0.1:5139:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: ${DB_NAME:-timecrax}
      DB_USER: ${DB_USER:-timecrax}
      DB_PASSWORD: ${DB_PASSWORD:-}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY:-}
      SMTP_USERNAME: ${SMTP_USERNAME:-}
      SMTP_PASSWORD: ${SMTP_PASSWORD:-}
      SMTP_FROM_EMAIL: ${SMTP_FROM_EMAIL:-}
      FRONTEND_URL: ${FRONTEND_URL:-https://timecrax.ipb.pt}
      SEED_DATABASE: ${SEED_DATABASE:-}
      VIRTUAL_HOST: timecrax.ipb.pt
      VIRTUAL_PORT: 8080
      VIRTUAL_PATH: /api/
      VIRTUAL_DEST: /
      LETSENCRYPT_HOST: timecrax.ipb.pt
    volumes:
      - timecrax_storage:/data/storage
    networks:
      - app
      - net
    depends_on:
      - db

volumes:
  timecrax_pgdata:
  timecrax_pgadmin_data:
  timecrax_storage:

networks:
  app:
    driver: bridge
  internal:
    internal: true
  net:
    external: true
