// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Timecrax.Api.Data;

#nullable disable

namespace Timecrax.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251222061145_AddThemesAchievementsQuizzes")]
    partial class AddThemesAchievementsQuizzes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("app")
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Timecrax.Api.Domain.Entities.Achievement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Image")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("achievements", "app");
                });

            modelBuilder.Entity("Timecrax.Api.Domain.Entities.CorrelationQuiz", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("EventCardId")
                        .HasColumnType("uuid");

                    b.Property<string>("Image1")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Image2")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Image3")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Text1")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Text2")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Text3")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EventCardId")
                        .IsUnique();

                    b.ToTable("correlation_quizzes", "app");
                });

            modelBuilder.Entity("Timecrax.Api.Domain.Entities.EventCard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("DCEra")
                        .HasColumnType("boolean");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.Property<Guid>("ThemeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ThemeId", "CreatedAt");

                    b.ToTable("event_cards", "app", t =>
                        {
                            t.HasCheckConstraint("ck_event_cards_year", "\"Year\" > 0");
                        });
                });

            modelBuilder.Entity("Timecrax.Api.Domain.Entities.ImageQuiz", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<short>("CorrectImageIndex")
                        .HasColumnType("smallint");

                    b.Property<Guid>("EventCardId")
                        .HasColumnType("uuid");

                    b.Property<string>("Image1")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Image2")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Image3")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Image4")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EventCardId")
                        .IsUnique();

                    b.ToTable("image_quizzes", "app", t =>
                        {
                            t.HasCheckConstraint("ck_image_quizzes_correct", "\"CorrectImageIndex\" BETWEEN 0 AND 3");
                        });
                });

            modelBuilder.Entity("Timecrax.Api.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IpAddress")
                        .HasColumnType("text");

                    b.Property<string>("ReplacedByTokenHash")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserAgent")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("refresh_tokens", "app");
                });

            modelBuilder.Entity("Timecrax.Api.Domain.Entities.TextQuiz", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<short>("CorrectTextIndex")
                        .HasColumnType("smallint");

                    b.Property<Guid>("EventCardId")
                        .HasColumnType("uuid");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Text1")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Text2")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Text3")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Text4")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EventCardId")
                        .IsUnique();

                    b.ToTable("text_quizzes", "app", t =>
                        {
                            t.HasCheckConstraint("ck_text_quizzes_correct", "\"CorrectTextIndex\" BETWEEN 0 AND 3");
                        });
                });

            modelBuilder.Entity("Timecrax.Api.Domain.Entities.Theme", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatorUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Image")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CreatorUserId");

                    b.HasIndex("CreatorUserId", "Name")
                        .IsUnique();

                    b.ToTable("themes", "app");
                });

            modelBuilder.Entity("Timecrax.Api.Domain.Entities.TrueOrFalseQuiz", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("EventCardId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsTrue")
                        .HasColumnType("boolean");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EventCardId")
                        .IsUnique();

                    b.ToTable("true_or_false_quizzes", "app");
                });

            modelBuilder.Entity("Timecrax.Api.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Picture")
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SchoolName")
                        .HasColumnType("text");

                    b.Property<int>("Score")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users", "app");
                });

            modelBuilder.Entity("Timecrax.Api.Domain.Entities.UserAchievement", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AchievementId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("AchievedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId", "AchievementId");

                    b.HasIndex("AchievementId");

                    b.ToTable("user_achievements", "app");
                });

            modelBuilder.Entity("Timecrax.Api.Domain.Entities.UserCompletedTheme", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ThemeId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId", "ThemeId");

                    b.HasIndex("ThemeId");

                    b.HasIndex("UserId", "CompletedAt");

                    b.ToTable("user_completed_themes", "app");
                });

            modelBuilder.Entity("Timecrax.Api.Domain.Entities.CorrelationQuiz", b =>
                {
                    b.HasOne("Timecrax.Api.Domain.Entities.EventCard", "EventCard")
                        .WithOne("CorrelationQuiz")
                        .HasForeignKey("Timecrax.Api.Domain.Entities.CorrelationQuiz", "EventCardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EventCard");
                });

            modelBuilder.Entity("Timecrax.Api.Domain.Entities.EventCard", b =>
                {
                    b.HasOne("Timecrax.Api.Domain.Entities.Theme", "Theme")
                        .WithMany("EventCards")
                        .HasForeignKey("ThemeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Theme");
                });

            modelBuilder.Entity("Timecrax.Api.Domain.Entities.ImageQuiz", b =>
                {
                    b.HasOne("Timecrax.Api.Domain.Entities.EventCard", "EventCard")
                        .WithOne("ImageQuiz")
                        .HasForeignKey("Timecrax.Api.Domain.Entities.ImageQuiz", "EventCardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EventCard");
                });

            modelBuilder.Entity("Timecrax.Api.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("Timecrax.Api.Domain.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Timecrax.Api.Domain.Entities.TextQuiz", b =>
                {
                    b.HasOne("Timecrax.Api.Domain.Entities.EventCard", "EventCard")
                        .WithOne("TextQuiz")
                        .HasForeignKey("Timecrax.Api.Domain.Entities.TextQuiz", "EventCardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EventCard");
                });

            modelBuilder.Entity("Timecrax.Api.Domain.Entities.Theme", b =>
                {
                    b.HasOne("Timecrax.Api.Domain.Entities.User", "CreatorUser")
                        .WithMany("CreatedThemes")
                        .HasForeignKey("CreatorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatorUser");
                });

            modelBuilder.Entity("Timecrax.Api.Domain.Entities.TrueOrFalseQuiz", b =>
                {
                    b.HasOne("Timecrax.Api.Domain.Entities.EventCard", "EventCard")
                        .WithOne("TrueOrFalseQuiz")
                        .HasForeignKey("Timecrax.Api.Domain.Entities.TrueOrFalseQuiz", "EventCardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EventCard");
                });

            modelBuilder.Entity("Timecrax.Api.Domain.Entities.UserAchievement", b =>
                {
                    b.HasOne("Timecrax.Api.Domain.Entities.Achievement", "Achievement")
                        .WithMany("UserAchievements")
                        .HasForeignKey("AchievementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Timecrax.Api.Domain.Entities.User", "User")
                        .WithMany("Achievements")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Achievement");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Timecrax.Api.Domain.Entities.UserCompletedTheme", b =>
                {
                    b.HasOne("Timecrax.Api.Domain.Entities.Theme", "Theme")
                        .WithMany("CompletedByUsers")
                        .HasForeignKey("ThemeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Timecrax.Api.Domain.Entities.User", "User")
                        .WithMany("CompletedThemes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Theme");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Timecrax.Api.Domain.Entities.Achievement", b =>
                {
                    b.Navigation("UserAchievements");
                });

            modelBuilder.Entity("Timecrax.Api.Domain.Entities.EventCard", b =>
                {
                    b.Navigation("CorrelationQuiz")
                        .IsRequired();

                    b.Navigation("ImageQuiz")
                        .IsRequired();

                    b.Navigation("TextQuiz")
                        .IsRequired();

                    b.Navigation("TrueOrFalseQuiz")
                        .IsRequired();
                });

            modelBuilder.Entity("Timecrax.Api.Domain.Entities.Theme", b =>
                {
                    b.Navigation("CompletedByUsers");

                    b.Navigation("EventCards");
                });

            modelBuilder.Entity("Timecrax.Api.Domain.Entities.User", b =>
                {
                    b.Navigation("Achievements");

                    b.Navigation("CompletedThemes");

                    b.Navigation("CreatedThemes");

                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
